name: Deploy Storybook
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install
          echo "Dependencies installed successfully"

      - name: Build packages
        run: |
          echo "Building all packages..."
          pnpm build
          echo "Packages built successfully"

      - name: Build Storybook
        run: |
          echo "Building Storybook..."
          cd apps/docs
          pnpm build-storybook --debug
          echo "Storybook build output:"
          ls -la storybook-static
          echo "Checking for index.html:"
          cat storybook-static/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "apps/docs/storybook-static"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Post Deployment Check
        run: |
          echo "Deployment completed"
          echo "Checking final build output:"
          ls -la apps/docs/storybook-static
          echo "You can view the documentation at: https://jjhoncv.github.io/ajk-ui-components/"
